In [3]:
import numpy as np

## 38. Load local data file (no missing data inside)
<pre>Given Input:
local filename: irsi.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
...
       (5.9, 3. , 5.1, 1.8, 'Iris-virginica')],</pre>
dtype=[('sepallength', '<f4'), ('sepalwidth', '<f4'), ('petallength', '<f4'), ('petalwidth', '<f4'), ('species', 'O')])

In [6]:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
data

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iri

#### np.loadtxt( ) is equivalent function to np.genfromtxt( ) when no data is missing.

## 39. min, max, standard deviation, mean of numpy array
<pre>Find the min, max, standard deviation, mean of 
'sepallength', 'sepalwidth', 'petallength', and 'petalwidth' respectively.

Given Input:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
Desired Output:
$> 7.9
$> 2.0
$> 1.7585291
$> 1.1986667
</pre>

In [129]:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})

In [122]:
data['sepallength'].max()

7.9

In [126]:
data['sepalwidth'].min()

2.0

In [128]:
data['petallength'].std()

1.7585291

In [127]:
data['petalwidth'].mean()

1.1986667

## 40. Sort array by column
<pre>Sort by sepallength 
Given Input:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})

Desired Output:
array([(4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iris-setosa'),
</pre>

In [ ]:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})

In [131]:
data[data['sepallength'].argsort()]

array([(4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (4.6, 3.2, 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.3, 'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, 'Iris-setosa'),
       (4.9, 2.4, 3.3, 1. , 'Iris-versicolor'),
       (4.9, 2.5, 4.5, 1.7, 'Iris-virginica'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (5. , 3.5, 1.3, 0.

## 41. Find the count number of a condition column
<pre>Find the number of sample that the pentallength greater than its mean.
Given Input:
The previous imported iris data

Desired Output:
$> 93
</pre>

In [143]:
np.count_nonzero(data[data['petallength'] > data['petallength'].mean()])

93

## 42. Find the mode (most frequent) value in numpy array
<pre>Find the mode of sepalwidth
Given Input:
The previous imported iris data

Desired Output:
$> 3</pre>

In [152]:
vals, counts = np.unique(data['sepalwidth'], return_counts=True)
print(vals[np.argmax(counts)])

3.0


## 43. Shuffle the rows of the dataset
<pre>
Given Input:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
$> data
array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       ....
Desired Output:       
$> data
array([(5.2, 3.4, 1.4, 0.2, 'Iris-setosa'),
       (6. , 2.9, 4.5, 1.5, 'Iris-versicolor'),
       (4.8, 3.1, 1.6, 0.2, 'Iris-setosa'),
       (5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'),
</pre>

In [179]:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})

In [185]:
np.random.shuffle(data)

In [186]:
data

array([(5.2, 3.4, 1.4, 0.2, 'Iris-setosa'),
       (6. , 2.9, 4.5, 1.5, 'Iris-versicolor'),
       (4.8, 3.1, 1.6, 0.2, 'Iris-setosa'),
       (5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'),
       (5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'),
       (7.7, 3.8, 6.7, 2.2, 'Iris-virginica'),
       (5.6, 3. , 4.1, 1.3, 'Iris-versicolor'),
       (5.2, 3.5, 1.5, 0.2, 'Iris-setosa'),
       (6.9, 3.1, 5.4, 2.1, 'Iris-virginica'),
       (4.8, 3. , 1.4, 0.3, 'Iris-setosa'),
       (6.7, 3.1, 5.6, 2.4, 'Iris-virginica'),
       (6.7, 3.3, 5.7, 2.5, 'Iris-virginica'),
       (6. , 2.2, 5. , 1.5, 'Iris-virginica'),
       (4.9, 2.5, 4.5, 1.7, 'Iris-virginica'),
       (6.5, 3. , 5.8, 2.2, 'Iris-virginica'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (5.1, 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (5.1, 3.3, 1.7, 0.5, 'Iris-setosa'),
       (6.4, 3.2, 5.3, 2.3, 'Iris-virginica'),
       (5.5, 2.4, 3.7, 1. , 'Iris-versicolor'),
       (6.3, 3.3, 4.7, 1.6, 'Iri

## 44. Compute the 10th and 90th percentile of the sepalwidth
<pre>Given Input:
The previous imported iris data

Desired Output:
10th percentile of the sepalwidth:  2.5
90th percentile of the sepalwidth:  3.6099999189376826
</pre>

In [192]:
print("10th percentile of the sepalwidth: ", 
      np.percentile(data['sepalwidth'], 10) )

10th percentile of the sepalwidth:  2.5


In [191]:
print("90th percentile of the sepalwidth: ",
      np.percentile(data['sepalwidth'], 90) )

90th percentile of the sepalwidth:  3.6099999189376826


## 45. Show dataset's shape and dtype
<pre>Given Input:
The previous imported iris data

Desired Output:
(150,)
</pre>
dtype([('sepallength', '<f4'), ('sepalwidth', '<f4'), ('petallength', '<f4'), ('petalwidth', '<f4'), ('species', 'O')])

In [193]:
data.shape

(150,)

In [194]:
data.dtype

dtype([('sepallength', '<f4'), ('sepalwidth', '<f4'), ('petallength', '<f4'), ('petalwidth', '<f4'), ('species', 'O')])

## 46. Creating a numpy array with an ellipsis
<pre>Access first column of array using ellipsis "..."
Given Input:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])
$> arr
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])   
       
Desired Output:  
[1 5]    
</pre>

In [208]:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [209]:
print(arr[..., 0])

[1 5]


## 47. Using broadcasting to perform element-wise operations
<pre>Transpose arr2 and add arr1
Given Input:
arr1 = np.array([[1, 2], [3, 4], [5,6]])
arr2 = np.array([2, 3, 4])

Desired Output:  
array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])
</pre>

In [219]:
arr1 = np.array([[1, 2], [3, 4], [5,6]])
arr2 = np.array([2, 3, 4])

In [220]:
arr1 + arr2.reshape(3, 1)

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])

## 48. Using broadcasting to perform element-wise operations
<pre>Transpose arr2 and multiply arr1
Given Input:
arr1 = np.array([[1, 2], [3, 4], [5,6]])
arr2 = np.array([2, 3, 4])

Desired Output:
array([[ 2,  4],
       [ 9, 12],
       [20, 24]])    

In [221]:
arr1 * arr2.reshape(3, 1)

array([[ 2,  4],
       [ 9, 12],
       [20, 24]])

## 49. Solve linear algebra
<pre>
Find the value of a and b
1a + 2b = 5
3a + 4b = 6

Desired Output:
[-4.   4.5]
</pre>

In [223]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.solve(a, b)
print(x)

[-4.   4.5]


## 50. Solve linear algebra
<pre>Find the value of x y, and z
3x + 4y + 2z = 1
2x + 5y + 3z = 2
x + 2y + z = 3

Desired Output:
[ -5.  12. -16.]</pre>

In [229]:
a = np.array([[3, 4, 2], [2, 5, 3], [1, 2, 1]])
b = np.array([1, 2, 3])
x = np.linalg.solve(a, b)
print(x)

[ -5.  12. -16.]


## 51. Numpy array broadcasting - Scalar multiplication
<pre>Find the broadcasting of a * b
Given Input:
a = np.array([[1, 2], [3, 4]])
b = 2

Desired Output:
[[2 4]
 [6 8]]</pre>

In [230]:
a = np.array([[1, 2], [3, 4]])
b = 2
c = a * b
print(c)

[[2 4]
 [6 8]]


## 51. Numpy array broadcasting - 2D array multiplication
<pre>Find the broadcasting of a * b
Given Input:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([2, 3])

Desired Output:
[[ 2  6]
 [ 6 12]
 [10 18]]

In [239]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([2, 3])
c = a * b
print(c)

[[ 2  6]
 [ 6 12]
 [10 18]]


## 52. Numpy array broadcasting - 3D array multiplication
<pre>Find the broadcasting of a * b
Given Input:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([10, 20])

Desired Output:
[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]</pre>

In [235]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([10, 20])
c = a + b 
print(c)

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [234]:
a.shape

(2, 2, 2)

In [240]:
b.shape

(2,)