In [1]:
import numpy as np

## 20. Create a 2D array containing random floats between 5 and 10
<pre>Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

Desired Output:
array([[5.07634273, 7.32940897, 5.78840303],
       [9.53547942, 7.16008125, 7.67112179],
       [7.42716913, 9.014935  , 9.20378359],
       [6.28776986, 5.7333183 , 6.7932973 ],
       [8.92046486, 7.80469775, 7.51347921]])</pre>

In [2]:
np.random.uniform(5,10, size=(5,3))

array([[7.28971239, 9.83082907, 5.74887922],
       [8.86273344, 5.3705823 , 9.86869233],
       [6.50522968, 9.51569933, 5.37464999],
       [5.76716404, 6.16647355, 5.32844923],
       [5.48013589, 8.25501796, 7.26970935]])

## 21. Print only 3 decimal places in python numpy array
<pre>Print or show only 3 decimal places of the numpy array rand_arr.

Given Input:
rand_arr = np.random.random((2,2))</pre>

In [3]:
rand_arr = np.random.random([2,2])
rand_arr

array([[0.27317629, 0.62939944],
       [0.23066   , 0.95621408]])

In [4]:
np.round(rand_arr,3)

array([[0.273, 0.629],
       [0.231, 0.956]])

## 22. Print a scientific notation (like 1e10) numpy array to standard notation
<pre>Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Given Input:
rand_arr = np.random.random([3,3])/1e3
rand_arr
$> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
          [  8.447761e-04,   4.718856e-06,   1.215691e-04],
          [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:
$> array([[ 0.000543,  0.000278,  0.000425],
          [ 0.000845,  0.000005,  0.000122],
          [ 0.000671,  0.000826,  0.000137]])</pre>

In [5]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[8.91778182e-05, 6.62826688e-05, 9.14705143e-04],
       [2.04135377e-04, 3.94825989e-04, 4.77296823e-04],
       [7.84455091e-04, 2.77446886e-04, 2.33903304e-04]])

In [6]:
np.set_printoptions(suppress=True, precision=6)  
rand_arr

array([[0.000089, 0.000066, 0.000915],
       [0.000204, 0.000395, 0.000477],
       [0.000784, 0.000277, 0.000234]])

In [7]:
np.set_printoptions(suppress=False)  
rand_arr

array([[8.917782e-05, 6.628267e-05, 9.147051e-04],
       [2.041354e-04, 3.948260e-04, 4.772968e-04],
       [7.844551e-04, 2.774469e-04, 2.339033e-04]])

## 23. Limit the number of items printed in output of numpy array
<pre>Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Given Input:
a = np.arange(15)
$> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:
$> array([ 0,  1,  2, ..., 12, 13, 14])
</pre>

In [8]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

## 24. Print the full numpy array without truncating
<pre>Print the full numpy array a without truncating.

Given Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
a
$> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:
a
$> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])</pre>

In [9]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [10]:
np.set_printoptions(threshold=np.Inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. Import a dataset with numbers and texts keeping the text intact in python numpy
<pre>Import the iris dataset keeping the text intact.
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       ...
</pre>

In [11]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',',  dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

## 26. Compute the mean, median, standard deviation of a numpy array
<pre>Find the mean, median, standard deviation of iris's sepallength (1st column)
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
[5.843333333333334, 5.8, 0.8253012917851409]
</pre>

In [12]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [13]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print([mu, med, sd])

[5.843333333333334, 5.8, 0.8253012917851409]


## 27. Find the percentile scores of a numpy array
<pre>Find the 5th and 95th percentile of iris's sepallength

Given Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0]) 

Desired Output:
array([4.6  , 7.255])</pre>


In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

## 28. Find the position of missing value in numpy array
<pre>
Find: 
1. Number of missing values
2. Row number that contains missing values
3. The NaN row value

Given Input:
arr = np.array([[1, 2, 3],
                [4, np.NaN, 6],
                [7, 8, 9],
                [np.NaN, np.NaN, np.NaN]
               ])

Desired Output:
Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]</pre>

In [15]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [nan, nan, nan]])

In [16]:
print("Number of missing values: \n", np.isnan(arr).sum())
print("Row contains missing values: \n", 
                      np.where(np.any(np.isnan(arr)==True,axis=1)) )
print("The NaN row: \n",arr[np.where(np.any(np.isnan(arr)==True,axis=1))])

Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]


## 29. Filter with conditions
<pre>
Filter the first column < 9 and fourth column > 4
Given Input:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])

Desired Output:
$> arr[conditions]
array([[5, 6, 7, 8]])

In [17]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
conditions = (arr[:, 0] < 9) & (arr[:, 3] > 4)

In [19]:
arr[conditions]

array([[5, 6, 7, 8]])

## 30. Inverse set of array
<pre>Multiply the non-NaN array by 2
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]
$> array([[ 4., nan,  6.],
         [nan, nan, nan]])
         
Desired Output:
array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

In [20]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]

array([[ 4., nan,  6.],
       [nan, nan, nan]])

### ~ means the inverse set of given array

In [21]:
arr[~np.any(np.isnan(arr), axis=1)] * 2

array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

## 31. Drop rows that contain a missing value from a numpy array
<pre>
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
               
Desired Output:
array([[1., 2., 3.],
       [7., 8., 9.]])
</pre>

In [22]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])

In [23]:
arr = arr[~np.any(np.isnan(arr), axis=1)]
arr

array([[1., 2., 3.],
       [7., 8., 9.]])

## 32. Find the correlation between two numpy array
<pre>
Find the correlation of array a and b
Given Input:
a = np.random.random(size=5)
b = np.random.random(size=5)
$> a
array([0.384083, 0.813738, 0.869471, 0.410821, 0.669355])
$> b
array([0.384083, 0.813738, 0.869471, 0.410821, 0.669355])

Desired Output:
$> array([[1.      , 0.184966],
       [0.184966, 1.      ]])</pre>


In [24]:
a = np.random.random(size=5)
b = np.random.random(size=5)

In [25]:
a

array([0.377191, 0.033956, 0.169348, 0.558323, 0.809845])

In [26]:
b

array([0.38564 , 0.281109, 0.582122, 0.496087, 0.543999])

In [27]:
np.corrcoef(a, b)

array([[1.      , 0.519918],
       [0.519918, 1.      ]])

## 33. Count NaN and non-NaN in numpy array
<pre> 
Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> There are 5 non-NaN.
$> There are 3 NaN.</pre> 


In [28]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [29]:
print(f"There are {np.count_nonzero(~np.isnan(arr))} non-NaN.")

There are 5 non-NaN.


In [30]:
print(f"There are {np.count_nonzero(np.isnan(arr))} NaN.")

There are 3 NaN.


## 34. Replace all missing values with 0 in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> array([0., 1., 2., 3., 0., 5., 0., 0.])
</pre> 

In [31]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [32]:
arr[np.isnan(arr)] = 0
arr

array([0., 1., 2., 3., 0., 5., 0., 0.])

## 35. Replace all missing values with mean in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])

Desired Output:
$> arr
array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])</pre>

In [33]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [34]:
arr[np.isnan(arr)] = np.mean(arr[~np.isnan(arr)])
arr

array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])

## 36. Find the count of unique values in a numpy array
<pre>Given Input:
$> stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
$> stud_gender
['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

Desired Output:</pre>
(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

In [35]:
stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
stud_gender

['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

In [36]:
np.unique(stud_gender)

array(['Female', 'Male'], dtype='<U6')

In [37]:
np.unique(stud_gender, return_counts=True)

(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

## 37. Convert numeric value to categoric value
<pre>Given Input:
$> stud_result = np.random.randint(0, 100, size=50)
$> stud_result
array([ 9, 86,  6, 67, 14, 64, 18, 83,  5, 66, 15, 68, 66, 58,  1, 64,  8,
       64, 97, 12, 45, 12,  1,  0, 21, 75, 12, 15, 46, 76, 50, 21,  2, 31,
        5, 54, 91, 48, 10, 89, 52, 61, 52, 85, 40, 28,  3, 29, 20, 40])

Desired Output:
Categorize the reult in 'Fail':below 50, 'Pass':blow 70, 'Good':below 100'
</pre>

In [38]:
stud_result = np.random.randint(0, 100, size=50)
stud_result

array([45, 52, 15, 15, 55, 59, 67, 97, 32, 29, 76, 55, 59, 17,  1, 12, 55,
       13,  1, 36, 66, 48, 59, 12, 62, 40, 90, 37, 45, 86, 29, 94, 36, 83,
       66, 44, 34, 53,  2, 75, 41, 35, 70, 35,  9,  1, 87, 89, 50, 94])

In [39]:
# digitize the result in to 4 ranges 
cat = np.digitize(stud_result, np.array([0, 50, 70, 100]))
cat

array([1, 2, 1, 1, 2, 2, 2, 3, 1, 1, 3, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 1, 2, 1, 3, 1, 1, 3, 1, 3, 1, 3, 2, 1, 1, 2, 1, 3, 1, 1, 3, 1,
       1, 1, 3, 3, 2, 3])

In [40]:
cat_label = {1:'Fail', 2:'Pass', 3:'Good'}

In [41]:
result_in_cat = [cat_label[x] for x in cat]
result_in_cat

['Fail',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Pass',
 'Pass',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Pass',
 'Pass',
 'Fail',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Good']