# Universal Function

In [1]:
import numpy as np

## 53. Numpy power and square root
<pre>Find the following value in numpy array
1. Power 2 of array([1, 2, 3])
2. Square root of array([4, 9, 16])

Desire Output:
$> [1 4 9]
$> [2. 3. 4.]</pre>

In [6]:
a = np.array([1, 2, 3])
c = np.power(a, 2)
print(c)

[1 4 9]


In [4]:
a = np.array([4, 9, 16])
c = np.sqrt(a)
print(c)

[2. 3. 4.]


## 54. Negation of numpy boolean array
<pre>Find the negation of array
Given Input:
a = np.array([True, False, True])

Desired Output:
not a: [False  True False]</pre>

In [7]:
a = np.array([True, False, True])
neg_a = np.logical_not(a)
print("not a:", neg_a)

not a: [False  True False]


## 55. Element-wise logical operations on two arrays
<pre>Find the logical value of a and b
Given Input:
a = np.array([False, True, False, True])
b = np.array([False, False, True, True])

Desired Output:
a and b: [False False False  True]
a or b: [False  True  True  True]
a xor b: [False  True  True False]</pre>

In [10]:
a = np.array([False, True, False, True])
b = np.array([False, False, True, True])

and_ab = np.logical_and(a, b)
or_ab = np.logical_or(a, b)
xor_ab = np.logical_xor(a, b)

print("a and b:", and_ab)
print("a or b:", or_ab)
print("a xor b:", xor_ab)

a and b: [False False False  True]
a or b: [False  True  True  True]
a xor b: [False  True  True False]


## 56. Performs unbuffered in place operation on operand
<pre>Make negative the a first and second column, and return a
Given Input:
a = np.array([1, 2, 3, 4])

Desired Output:
array([-1, -2,  3,  4])</pre>

In [11]:
a = np.array([1, 2, 3, 4])
np.negative.at(a, [0, 1])
a

array([-1, -2,  3,  4])

## 57. Performs unbuffered in place operation on operand
<pre>Add items 0 and 1 in a to b, and store results in a
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])

Desired Output:
$> a
array([2, 4, 3, 4])</pre>

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])
np.add.at(a, [0, 1], b)
a

array([2, 4, 3, 4])

## 58. Accumulate the result of applying the operator to all elements
<pre>Find the accumulate value by addition and multiplication of a
Given Input:
a = np.array([1, 2, 3])

Desired Output:
array([1, 3, 6])
array([1, 2, 6])
</pre>

In [15]:
a = np.array([1, 2, 3])

In [16]:
# np.add.accumulate() equal np.cumsum()
np.add.accumulate(a)

array([1, 3, 6])

In [17]:
np.multiply.accumulate(a)

array([1, 2, 6])

## 59. Reduces array’s dimension by one, by applying ufunc along one axis.
<pre>Try the folowing 3 function and write down its calcualting logics 
np.multiply.reduce(a)
np.add.reduce(a)
np.power.reduce(a)

Given Input:
a = np.array([2,3,4])

Desired Output:
24
9
4096</pre>

In [21]:
a = np.array([2,3,4])

In [22]:
# = 2*3*4
np.multiply.reduce(a)

24

In [26]:
# np.add.reduce() equal to np.sum()
np.add.reduce(a)

9

In [27]:
# = (2**3)**4
np.power.reduce(a)

4096

## 60. Compute the outer product of two given vectors
<pre>
Given Input:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 

Desired Output:
array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])</pre>

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 

In [36]:
np.multiply.outer(a, b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [41]:
np.multiply(a, b)

array([ 4, 10, 18])

## 61. First array elements raised to powers from second array
<pre>Use np.float_power(x1, x2) to the positionally-corresponding power
Given Input:
a = np.array([1, 2, 3])
b = np.array([0, 2, 4])

Desired Output:
array([ 1.,  4., 81.])</pre>

In [42]:
a = np.array([1, 2, 3])
b = np.array([0, 2, 4])

In [43]:
np.float_power(a, b)

array([ 1.,  4., 81.])

## 62. Returns the element-wise remainder of division
<pre>Find the remainder of division from a b
Given Input:
a = np.array([3, 5, 7])
b = np.array([2, 3, 4])

Desired Output:
array([1, 2, 3])</pre>

In [48]:
a = np.array([3, 5, 7])
b = np.array([2, 3, 4])

In [49]:
np.remainder(a, b)

array([1, 2, 3])

In [50]:
# The % operator can be used as a shorthand for np.remainder on ndarrays
a % b

array([1, 2, 3])

In [51]:
np.mod(a, b)

array([1, 2, 3])

## 63. Floor divide
<pre>Return the largest integer smaller or equal to the division of the inputs.
Given Input:
a = np.array([7, 7, 7, 11])
b = np.array([2, 3, 4, 5])

Desired Output:
array([3, 2, 1, 2])</pre>

In [62]:
a = np.array([7, 7, 7, 11])
b = np.array([2, 3, 4, 5])

In [63]:
np.floor_divide(a, b)

array([3, 2, 1, 2])

## 64. Natural logarithm, element-wise
<pre>
Try Natural logarithm: np.log()
Try Natural logarithm of one plus log(1 + x): np.log1p()

Given Input:
a = np.array([1, 10, np.e])

Desired Output:
array([0.        , 2.30258509, 1.        ])
array([0.69314718, 2.39789527, 1.31326169])</pre>

In [78]:
a = np.array([1, 10, np.e])

In [79]:
np.log(a)

array([0.        , 2.30258509, 1.        ])

In [80]:
np.log1p(a)

array([0.69314718, 2.39789527, 1.31326169])

## 65. Calculate the exponential of all elements in the input array
<pre>Calculate exp(x)
Calculate exp(x) - 1

Given Input:
a = np.array([1, 10, 100])

Desired Output:
array([2.71828183e+00, 2.20264658e+04, 2.68811714e+43])
array([1.71828183e+00, 2.20254658e+04, 2.68811714e+43])
</pre>

In [85]:
a = np.array([1, 10, 100])

In [88]:
np.exp(a)

array([2.71828183e+00, 2.20264658e+04, 2.68811714e+43])

In [89]:
np.expm1(a)

array([1.71828183e+00, 2.20254658e+04, 2.68811714e+43])

## 66. Return the non-negative square-root of an array, element-wise.
<pre>Return square root of array
a = np.array([1, 10, 100])</pre>

In [ ]:
a = np.array([1, 10, 100])

In [90]:
np.sqrt(a)

array([ 1.        ,  3.16227766, 10.        ])

## 67. Return the cube-root of an array, element-wise.
<pre>Return cube root of array
a = np.array([1, 8, 1000])</pre>

In [92]:
a = np.array([1, 8, 1000])

In [93]:
np.cbrt(a)

array([ 1.,  2., 10.])

## 68. Returns the greatest common divisor

In [97]:
np.gcd(12, 20)

4

In [110]:
np.gcd.reduce([15, 25, 35])

5

In [108]:
np.gcd(np.arange(6), 20)

array([20,  1,  2,  1,  4,  5])

## 69. Returns the lowest common multiple 

In [94]:
np.lcm(12, 20)

60

In [95]:
np.lcm.reduce([3, 12, 20])

60

In [96]:
np.lcm.reduce([40, 12, 20])

120

In [111]:
np.lcm(np.arange(6), 20)

array([ 0, 20, 20, 60, 20, 20])

## 70. Test element-wise for NaN and return result as a boolean array

In [117]:
np.isnan([1, 2, np.NaN])

array([False, False,  True])

In [118]:
np.isnan(np.inf)

False

## 71. Return the ceiling and floor of the input, element-wise.

In [129]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
a

array([-1.7, -1.5, -0.2,  0.2,  1.5,  1.7,  2. ])

In [127]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [128]:
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

## 72. Return the truncated value of the input, element-wise.
The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. In short, the fractional part of the signed number x is discarded.

In [130]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
a

array([-1.7, -1.5, -0.2,  0.2,  1.5,  1.7,  2. ])

In [131]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])